### ISSUE TITLE
error on OS/2

### ISSUE THREAD

**Issue by Tellie** [BowDown097/innertube-qt#1]
Hi

I tried to compile it with qt v6.2.4 and failed with...

./lib/innertube-qt/src/innertube/endpoints/misc/getnotificationmenu.cpp: In constructor 'InnertubeEndpoints::GetNotificationMenu::GetNotificationMenu(const QString&, InnertubeContext*, CurlEasy*, InnertubeAuthStore*, const QString&)':
../lib/innertube-qt/src/innertube/endpoints/misc/getnotificationmenu.cpp:19:85: error: no match for 'operator[]' (operand types are 'QJsonValueRef' and 'int')
   19 |         const QJsonObject action = QJsonDocument::fromJson(data).object()["actions"][0].toObject();
      |                                                                                     ^
make: *** [Makefile:8437: getnotificationmenu.obj] Error 1

Any idea about error??

**Comment by BowDown097** [comment]
Just checked and it looks like the recent changes I did to make the JSON stuff less of a mess was only made possible in Qt 6.3. Well, that's annoying. I'm gonna work on getting this library to be fully compatible with Qt 5 soon (probably tomorrow) and I assume the fixes there will trickle down to your Qt version.

**Comment by BowDown097** [comment]
Builds on Qt 5.15 LTS for me now on latest commit (was gonna go for 5.6 support for XP users, but dropped the idea really quickly because the JSON library is hot garbage up until 5.10). Can you test it?

**Comment by Tellie** [comment]
Hihi

Tested with qt 5.15.2
It complains that it cannot find the x11extras, that's true as we don't
have that.
I turn that off, but it still gave the same error i had before.

But when running with qt v6.2.4  the build went ok, and now it's compiling
till the end.
Have now a running qttube 👍

Op ma 23 jan. 2023 02:31 schreef BowDown097 ***@***.***>:

**Comment by Tellie** [comment]
Hi

When I run it i see this output.
And when the video should start, it shutdown the program.
Then i see the line with
Js: The resource https://i.ijting.com/generate_204

Any idea on the output ??

**Comment by BowDown097** [comment]
That line is unrelated and just happens normally. Can you run it in Qt Creator's debugger and see what line of code it died on?

**Comment by Tellie** [comment]
Hi
We don't have Qtcreator and also unfortunately no gdb

But i get this now on a fresh build..

  142 |     InnertubeReply* reply =
InnerTube::instance().get<InnertubeEndpoints::Search>(query, "",
compiledParams);
      |
             ^
../src/ui/browsehelper.cpp:142:83: warning: left operand of comma operator
has no effect [-Wunused-value]
  142 |     InnertubeReply* reply =
InnerTube::instance().get<InnertubeEndpoints::Search>(query, "",
compiledParams);
      |
               ^~~~~
../src/ui/browsehelper.cpp:142:94: warning: right operand of comma operator
has no effect [-Wunused-value]
  142 |     InnertubeReply* reply =
InnerTube::instance().get<InnertubeEndpoints::Search>(query, "",
compiledParams);
      |
                          ^~~~~~~~~~~~~~
make: *** [Makefile:12840: browsehelper.obj] Error 1


Op di 24 jan. 2023 01:08 schreef BowDown097 ***@***.***>:

**Comment by BowDown097** [comment]
Well it's pretty hard to diagnose the issue without a debugger... But that line makes me curious if your compiler doesn't fully support concepts and that's why the crash is happening.
Update: Nevermind, I managed to get the warning too, seems to be a false positive or something.

**Comment by BowDown097** [comment]
Out of curiosity, did the latest commit to QtTube happen to fix it?

**Comment by Tellie** [comment]
Hi, 

Can't test ATM, as im on holiday for 20 days
